override HOST_PRIMARY_ARCH := host_x86_64
override HOST_32BIT_ARCH := host_i386
override HOST_FORCE_32BIT := -m32
override TARGET_PRIMARY_ARCH := target_armel
override TARGET_SECONDARY_ARCH := 
override TARGET_ALL_ARCH :=  target_armel 
override TARGET_FORCE_32BIT := 
override KERNELDIR := /home/rufus/mtk/kernel_3_16/kernel/
override KERNEL_ID := 3.16.0
override KERNEL_COMPONENTS := srvkm dc_drmmtk
override KERNEL_CROSS_COMPILE := armv7a-cros-linux-gnueabi-
override PVRSRV_MODNAME := pvrsrvkm
override PVR_BUILD_DIR := mt8135_linux
override PVR_BUILD_TYPE := release
override DISPLAY_CONTROLLER := dc_drmmtk
override PVR_SYSTEM := rgx_mtk
override BUILD := release
override DEBUGLINK := 1
override CACHEFLUSH_TYPE := CACHEFLUSH_GENERIC
override SUPPORT_INSECURE_EXPORT := 1
override SUPPORT_SECURE_EXPORT := 1
override PVR_HANDLE_BACKEND := idr
override SUPPORT_DRM := 1
override SUPPORT_DRM_DC_MODULE := 1
