#define SUPPORT_RGX 1
#define LINUX 
#define PVR_MMAP_USE_VM_INSERT 
#define PVR_LINUX_KMALLOC_ALLOCATION_THRESHOLD  16384 
#define SUPPORT_DRM 
#define SUPPORT_LINUX_X86_PAT 
#define PVR_LDM_DRIVER_REGISTRATION_NAME "pvrsrvkm"
#define PVR_LINUX_USING_WORKQUEUES 
#define PVR_LINUX_TIMERS_USING_WORKQUEUES 
#define CACHEFLUSH_TYPE CACHEFLUSH_GENERIC
#define SYS_USING_INTERRUPTS 
#define PVRSRV_ENABLE_PROCESS_STATS 
#define SUPPORT_SECURE_EXPORT 
#define GPUVIRT_VALIDATION_NUM_OS 8
#define PVR_LINUX_MISR_USING_PRIVATE_WORKQUEUE 
#define PVR_LINUX_HIGHORDER_ALLOCATION_THRESHOLD  256 
#define FIX_DUSTS_POW_ON_INIT 
#define PVRSRV_UNMAP_ON_SPARSE_CHANGE 
#define RGX_BVNC_CORE_KM_HEADER "cores/rgxcore_km_4.29.2.51.h"
#define PVRSRV_USE_VMAP_FOR_KERNEL_MAPPINGS 
#define PVR_LINUX_PHYSMEM_MAX_ALLOC_ORDER_NUM  2 
#define PVRSRV_MODNAME "pvrsrvkm"
#define SUPPORT_SERVER_SYNC 
#define LDM_PLATFORM 
#define PVR_LINUX_PHYSMEM_MAX_POOL_PAGES 10240
#define PVR_DRM_DRIVER_NAME "pvr"
#define PVR_BUILD_DIR "mt8173_linux"
#define SUPPORT_LINUX_X86_WRITECOMBINE 
#define RGX_BNC_CONFIG_KM_HEADER "configs/rgxconfig_km_4.V.2.51.h"
#define SUPPORT_PERCONTEXT_FREELIST 
#define SUPPORT_DBGDRV_EVENT_OBJECTS 
#define GPU_VIRTUALIZATION_NUM_OS 
#ifdef CONFIG_POWERVR_ROGUE_DEBUG
#define DEBUG_LINUX_MEM_AREAS 
#define DEBUG_HANDLEALLOC_KM 
#define SUPPORT_PAGE_FAULT_DEBUG 
#define PVR_BUILD_TYPE "debug"
#define RGXFW_ALIGNCHECKS 
#define DEBUG_LINUX_MEMORY_ALLOCATIONS 
#define DEBUG_LINUX_MMAP_AREAS 
#define PVR_RI_DEBUG 
#define DEBUG 
#define DEBUG_BRIDGE_KM 
#endif
#ifndef CONFIG_POWERVR_ROGUE_DEBUG
#define PVR_BUILD_TYPE "release"
#define RELEASE 
#endif
