pvrsrvkm-y += \
 server_breakpoint_bridge.o \
 server_cachegeneric_bridge.o \
 server_cmm_bridge.o \
 server_debugmisc_bridge.o \
 client_mm_bridge.o \
 client_pvrtl_bridge.o \
 client_sync_bridge.o \
 server_mm_bridge.o \
 server_pvrtl_bridge.o \
 server_regconfig_bridge.o \
 server_rgxcmp_bridge.o \
 server_rgxhwperf_bridge.o \
 server_rgxinit_bridge.o \
 server_rgxta3d_bridge.o \
 server_rgxtq_bridge.o \
 server_smm_bridge.o \
 server_srvcore_bridge.o \
 server_sync_bridge.o \
 server_syncexport_bridge.o \
 server_syncsexport_bridge.o \
 server_timerquery_bridge.o \
 cache_generic.o \
 connection_server.o \
 devicemem_heapcfg.o \
 devicemem_server.o \
 handle.o \
 lists.o \
 mmu_common.o \
 physheap.o \
 physmem.o \
 physmem_lma.o \
 pmr.o \
 power.o \
 process_stats.o \
 pvrsrv.o \
 scp.o \
 srvcore.o \
 sync_server.o \
 tlintern.o \
 tlserver.o \
 tlstream.o \
 debugmisc_server.o \
 rgxbreakpoint.o \
 rgxccb.o \
 rgxcompute.o \
 rgxdebug.o \
 rgxfwutils.o \
 rgxhwperf.o \
 rgxinit.o \
 rgxmem.o \
 rgxmmuinit.o \
 rgxpower.o \
 rgxregconfig.o \
 rgxsync.o \
 rgxta3d.o \
 rgxtimecorr.o \
 rgxtimerquery.o \
 rgxtransfer.o \
 rgxutils.o \
 allocmem.o \
 devicemem_mmap_stub.o \
 event.o \
 handle_idr.o \
 mm.o \
 mmap.o \
 mtk_module.o \
 module_common.o \
 osconnection_server.o \
 osfunc.o \
 ossecure_export.o \
 pdump.o \
 physmem_dmabuf.o \
 physmem_osmem_linux.o \
 physmem_tdmetacode_linux.o \
 physmem_tdsecbuf_linux.o \
 pvr_bridge_k.o \
 pvr_debug.o \
 pvr_debugfs.o \
 pvr_drm.o \
 pvr_drm_display.o \
 pvr_drm_gem.o \
 pvr_drm_prime.o \
 devicemem.o \
 devicemem_utils.o \
 dllist.o \
 hash.o \
 ra.o \
 sync.o \
 tlclient.o \
 uniq_key_splay_tree.o \
 rgx_compat_bvnc.o \
 mt8173/mt8173_mfgdvfs.o \
 mt8173/mt8173_mfgsys.o \
 mt8173/mt8173_sysconfig.o
ifeq ($(CONFIG_POWERVR_ROGUE_DEBUG),y)
pvrsrvkm-y += \
 client_devicememhistory_bridge.o \
 server_devicememhistory_bridge.o \
 client_ri_bridge.o \
 server_ri_bridge.o \
 devicemem_history_server.o \
 ri_server.o
endif
pvrsrvkm-$(CONFIG_X86) += osfunc_x86.o
pvrsrvkm-$(CONFIG_ARM) += osfunc_arm.o
pvrsrvkm-$(CONFIG_ARM64) += osfunc_arm64.o
pvrsrvkm-$(CONFIG_EVENT_TRACING) += trace_events.o
