mediatek-drm-objs := mediatek_drm_drv.o \
                  mediatek_drm_crtc.o \
                  mediatek_drm_fb.o \
                  mediatek_drm_output.o \
                  mediatek_drm_gem.o \
                  mediatek_drm_dsi.o \
                  mediatek_drm_debugfs.o \
                  mediatek_drm_hw-mt8173.o

obj-$(CONFIG_DRM_MEDIATEK) += mediatek-drm.o

