# MTK Platform Support
obj-$(CONFIG_SND_SOC_MT8135) += mt_afe_clk.o
obj-$(CONFIG_SND_SOC_MT8135) += mt_afe_control.o mt_afe_connection.o
obj-$(CONFIG_SND_SOC_MT8135) += mt8135_afe_pcm.o

# Machine support
obj-$(CONFIG_SND_SOC_MT8135_MT6397) += mt8135_evbp1.o
obj-$(CONFIG_SND_SOC_MT8135_MAX98090) += mt8135-max98090.o
