# MTK Platform Support
obj-$(CONFIG_SND_SOC_MT8173) += mtk_afe_control.o mtk_afe_connection.o
obj-$(CONFIG_SND_SOC_MT8173) += mt8173_afe_pcm.o

# Machine support
obj-$(CONFIG_SND_SOC_MT8173_MT6397) += mt8173_evb.o
obj-$(CONFIG_SND_SOC_MT8173_MAX98090) += mt8173-max98090.o

