# MTK Platform Support
obj-$(CONFIG_SND_SOC_MT8135) += mt_afe_clk.o
obj-$(CONFIG_SND_SOC_MT8135) += mt_afe_control.o mt_afe_connection.o
obj-$(CONFIG_SND_SOC_MT8135) += mt8135_afe_pcm.o
obj-$(CONFIG_SND_SOC_MT8135) += mt8135_evbp1.o
