mediatek-drm-objs := mediatek_drm_drv.o \
                  mediatek_drm_crtc.o \
                  mediatek_drm_fb.o \
                  mediatek_drm_output.o \
                  mediatek_drm_gem.o \
                  mediatek_drm_dmabuf.o \
                  mediatek_drm_dsi.o \
                  it6151.o \
                  mediatek_drm_debugfs.o \
                  mediatek_drm_ddp.o

obj-$(CONFIG_DRM_MEDIATEK) += mediatek-drm.o

